services:
  postgres:
    image: postgres:16
    container_name: drizzle_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drizzle
    ports:
      - "5432:5432"
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_replication_slots=10",
      "-c", "max_wal_senders=10"
    ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: